// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdP2Fk310dp6E7Po1f8sz6NC8pHTyA6dQ',
    appId: '1:769751446494:web:9d401ba5b583f68190e34f',
    messagingSenderId: '769751446494',
    projectId: 'selflearning-f5ed6',
    authDomain: 'selflearning-f5ed6.firebaseapp.com',
    storageBucket: 'selflearning-f5ed6.appspot.com',
    measurementId: 'G-HKGSYMSBMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9A216z-99TjTQYizCF3dJETRTWzcXW9I',
    appId: '1:769751446494:android:9ab0c8021c7b880190e34f',
    messagingSenderId: '769751446494',
    projectId: 'selflearning-f5ed6',
    storageBucket: 'selflearning-f5ed6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_i25vCKc56OZ5vMzfFxkZSL46p2Zb8o8',
    appId: '1:769751446494:ios:9ad1f93b6ce6c73890e34f',
    messagingSenderId: '769751446494',
    projectId: 'selflearning-f5ed6',
    storageBucket: 'selflearning-f5ed6.appspot.com',
    iosBundleId: 'com.self.learn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_i25vCKc56OZ5vMzfFxkZSL46p2Zb8o8',
    appId: '1:769751446494:ios:69af36fb25910b5e90e34f',
    messagingSenderId: '769751446494',
    projectId: 'selflearning-f5ed6',
    storageBucket: 'selflearning-f5ed6.appspot.com',
    iosBundleId: 'com.example.selfLearningApp',
  );
}
